
name: Build and Deploy GhPages docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        uses: olafurpg/setup-scala@v5
        run: sbt "clean; hepekDocs/hepek"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: gh-pages
          FOLDER: hepek-docs/target/web/public/main/docs
